name: Merge Safety Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-merge-safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check merge safety
        id: safety-check  # This ID will be used for the status check name
        uses: ExpediaGroup/github-helpers@v1  # Use the latest version; check the repo for updates
        with:
          helper: check-merge-safety
          github_token: ${{ secrets.MERGE_SAFETY_TOKEN }}  # Override with your PAT
          paths: '["payments/**", generations/**"]'  # Array of strings; adjust for your structure
          override_filter_paths: '["common/**"]'
