name: Merge Safety Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  service-check:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the latest PR branch tip
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      # 2️⃣ Fetch latest main branch
      - name: Fetch main
        run: |
          git fetch origin main:main

      # 3️⃣ Install yq for parsing YAML
      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      # 4️⃣ Load services config
      - name: Load services config
        id: load_config
        run: |
          SERVICES_FILE=".github/services.yml"
          if [ ! -f "$SERVICES_FILE" ]; then
            echo "Config file not found!"
            exit 1
          fi
          SERVICE_NAMES=($(yq e '.services | keys | .[]' $SERVICES_FILE))
          echo "services=${SERVICE_NAMES[*]}" >> $GITHUB_OUTPUT

      # 5️⃣ Check service conflicts
      - name: Check service conflicts
        id: service_check
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_SAFETY_TOKEN }}
        run: |
          set -e
          MERGE_BASE=$(git merge-base main HEAD)
          echo "Merge base: $MERGE_BASE"

          PR_FILES=$(git diff --name-only $MERGE_BASE HEAD)
          MAIN_FILES=$(git diff --name-only $MERGE_BASE main)

          echo "PR files:"
          echo "$PR_FILES"
          echo "Main files:"
          echo "$MAIN_FILES"

          BLOCK=false
          BLOCK_SERVICES=()

          for SERVICE in ${{ steps.load_config.outputs.services }}; do
            PATHS=$(yq e ".services.$SERVICE.paths[]" .github/services.yml)

            PR_MATCH=""
            MAIN_MATCH=""

            for PATTERN in $PATHS; do
              REGEX="^${PATTERN//\*\*/.*}$"
              PR_MATCH="$PR_MATCH
$(echo "$PR_FILES" | grep -E "$REGEX" || true)"
              MAIN_MATCH="$MAIN_MATCH
$(echo "$MAIN_FILES" | grep -E "$REGEX" || true)"
            done

            if [ "$SERVICE" = "common" ] && [ -n "$MAIN_MATCH" ]; then
              BLOCK=true
              BLOCK_SERVICES+=("$SERVICE")
            elif [ -n "$PR_MATCH" ] && [ -n "$MAIN_MATCH" ]; then
              BLOCK=true
              BLOCK_SERVICES+=("$SERVICE")
            fi
          done

          if [ "$BLOCK" = "true" ]; then
            echo "conflict=true" >> $GITHUB_OUTPUT
            echo "Blocking services: ${BLOCK_SERVICES[*]}"
            gh pr review ${{ github.event.pull_request.number }} \
              --repo ${{ github.repository }} \
              --request-changes \
              --body "PR conflicts with main in service(s): ${BLOCK_SERVICES[*]}"
          else
            echo "conflict=false" >> $GITHUB_OUTPUT
            gh pr review ${{ github.event.pull_request.number }} \
              --repo ${{ github.repository }} \
              --approve \
              --body "PR passes service-aware merge check."
          fi

      # 6️⃣ Fail if conflicts
      - name: Fail if conflicts
        if: steps.service_check.outputs.conflict == 'true'
        run: |
          echo "❌ PR conflicts detected in service(s). Please update branch."
          exit 1
