name: Merge Safety Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  service-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: git fetch origin main --unshallow

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Determine changed files
        id: changes
        run: |
          MERGE_BASE=$(git merge-base HEAD origin/main)
          PR_FILES=($(git diff --name-only origin/main...HEAD))
          MAIN_CHANGED=($(git diff --name-only $MERGE_BASE origin/main))
          
          echo "PR_FILES=${PR_FILES[*]}" >> $GITHUB_OUTPUT
          echo "MAIN_CHANGED=${MAIN_CHANGED[*]}" >> $GITHUB_OUTPUT
          echo "Changed in PR: ${PR_FILES[*]}"
          echo "Changed in main since branch point: ${MAIN_CHANGED[*]}"

      - name: Load services
        id: services
        run: |
          declare -A service_patterns
          for service in $(yq e '.services | keys | .[]' .github/services.yml); do
            patterns=$(yq e ".services.$service[]" .github/services.yml)
            service_patterns[$service]="$patterns"
          done
          # Export associative array for later steps
          declare -p service_patterns >> $GITHUB_ENV

      - name: Check affected services
        id: check
        run: |
          # Load environment
          eval "$(grep 'service_patterns' $GITHUB_ENV)"
          
          BLOCK=false
          PR_FILES=(${{ steps.changes.outputs.PR_FILES }})
          MAIN_CHANGED=(${{ steps.changes.outputs.MAIN_CHANGED }})
          MAIN_SET=()
          declare -A MAIN_MAP
          for f in "${MAIN_CHANGED[@]}"; do MAIN_MAP["$f"]=1; done

          for service in "${!service_patterns[@]}"; do
            IFS=$'\n' read -rd '' -a patterns <<< "${service_patterns[$service]}"
            SERVICE_BLOCK=false
            for f in "${PR_FILES[@]}"; do
              for pattern in "${patterns[@]}"; do
                if [[ $f == $pattern ]]; then
                  if [[ ${MAIN_MAP[$f]} ]]; then
                    echo "Service $service outdated: $f changed in main"
                    BLOCK=true
                  fi
                  SERVICE_BLOCK=true
                fi
              done
            done
            if [[ "$service" == "common" ]] && [[ "$SERVICE_BLOCK" == true ]]; then
              echo "Common service affected, marking block"
              BLOCK=true
            fi
          done
          
          echo "BLOCK=$BLOCK" >> $GITHUB_OUTPUT
          echo "BLOCK=$BLOCK"

      - name: Update GitHub PR status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MERGE_SAFETY_TOKEN }}
          script: |
            const context = github.context;
            const sha = context.payload.pull_request.head.sha;
            const blocked = '${{ steps.check.outputs.BLOCK }}' === 'true';
            const state = blocked ? 'failure' : 'success';
            const description = blocked
              ? 'Out-of-date files detected'
              : 'No conflicts with main. Safe to merge';
            
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: state,
              context: 'service-merge-check',
              description: description
            });
