name: Merge Safety Check

on:
  workflow_call:
  
permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  check-merge-safety:
    runs-on: ubuntu-latest
    name: Check Merge Safety
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch full history for accurate diff comparison
          fetch-depth: 0

      - name: Check Merge Safety
        uses: ExpediaGroup/github-helpers@main
        with:
          helper: check-merge-safety
          github_token: ${{ secrets.MERGE_SAFETY_TOKEN }}

          paths: |
            common/
            payments/
            generations/
          # Global files that should trigger merge safety checks for all projects
          override_filter_paths: |
            package.json
          # Alternative: use glob patterns for global files
          # override_filter_globs: |
          #   *.json
          #   *.lock
          #   .github/**
          #   **/Dockerfile
          # Files to ignore in merge safety checks
          ignore_globs: |
            **/docs/**
            **/.gitignore

